# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Fabric API
fabric_api_version=0.161.0+26.3
modmenu_version=21.0.0
clothconfig_version=26.3.158

minecraft_range=~26.3